package entity;
// Generated Apr 25, 2020 12:56:50 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int id;
     private Date joiningDate;
     private String name;
     private double salary;

    public Employee() {
    }

	
    public Employee(int id, double salary) {
        this.id = id;
        this.salary = salary;
    }
    public Employee(int id, Date joiningDate, String name, double salary) {
       this.id = id;
       this.joiningDate = joiningDate;
       this.name = name;
       this.salary = salary;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }




}


